---
title: "FARS access and summary functions"
author: "dmendres"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fars access and summary functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This is the vignette for the 'farsAssignment' package. 

The FARS (Fatality Accident Reporting System) data collected by the NTSE provides records fatal accident reports for a given year. The tools in this package enable reading, summarizing and plotting the FARs data for one or several years. The package also includes three years of FARS data.

## FARS data

Each of the FARS data files is in "comma separated value" format. Any of these data sets can be loaded with fars_read() as a data.frame (actually, a tbl_df). The data sets available in this package are:

* accident_2013.csv.bz2
* accident_2014.csv.bz2
* accident_2015.csv.bz2

The NHTSA Fatality Analysis Reporting System data is described [here](https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars)
The data contains 50 variables with column names as below:
```{r, cache=TRUE}
setwd("..")
source("R/fars_functions.R")
setwd("..")
farsDF2014 <- fars_read(make_filename(2014))
colnames(farsDF2014)
```

## FARS functions

* make_filename(year) will generate a file name in the appropriate format (e.g. "accident_[year].csv.bz2"")
* fars_read(filename) will return a tbl_df data.frame of the observations for the given year
* fars_read_years(filenames) will return a list of tbl_df data.frames with only the month and year retained for each fatality report
* fars_summarize_years will report, by year and month, the number of reports. 
* fars_map_state(state.code, year) wil plot the accident report locations for a give state.code.

## FARS functions examples


* make_filename(2014)

* fars_read("accident_2014.csv.bz2")

* fars_read_years(list(2013,2014))

* fars_summarize_years(list(2013, 2014, 2015))

* fars_map_state(1, 2014)






